### ISSUE TITLE
Search shows "undefined" when there's no page title

### ISSUE THREAD

**Issue by KieranHunt** [z3by/vuepress-plugin-flexsearch#17]
See the screenshot below:

![Screenshot 2020-05-06 at 08 46 31](https://user-images.githubusercontent.com/4106917/81145213-1d608880-8f76-11ea-9a06-5695e4c3b8e4.png)

vs the default search:

![Screenshot 2020-05-06 at 08 47 59](https://user-images.githubusercontent.com/4106917/81145316-513bae00-8f76-11ea-8e7d-61b042cbb6a8.png)

I suspect that this line is the issue:

https://github.com/z3by/vuepress-plugin-flexsearch/blob/908024c0bd463d6eff947d055106ae633671e2a6/SearchBox.vue#L220

whereas in the official plugin they do this:

https://github.com/vuejs/vuepress/blob/1114ade3d78863b3fd8510e327f100993dd8e1d1/packages/%40vuepress/plugin-search/SearchBox.vue#L36

(note the fallback to `s.path`)

---

I don't mind making the change to be more in-line with the official plugin if that's the direction you want to go?

**Comment by z3by** [comment]
Thanks for reporting this! yeah, I would appreciate a PR to fix this flaw.

**Comment by KieranHunt** [comment]
Hey I ended up going with a different library for this. I'll leave this open since I think it's still a bug.

✌️

**Comment by z3by** [comment]
This should be fixed in #18, please:
- Update Vuepress
- install version 0.1 of this plugin
- Try again

**Comment by z3by** [comment]
I am closing this because I assume it was fixed in #18.
