### ISSUE TITLE
cant't search page content only title

### ISSUE THREAD

**Issue by taojunnan** [z3by/vuepress-plugin-flexsearch#3]
`"vuepress": "^1.4.0"`

**Comment by z3by** [comment]
Hi, @taojianjian32 could you please explain the problem more? I tested the plugin with different versions and it works perfectly.

**Comment by taojianjian32** [comment]
Hi, @z3by I checked, It's my mistake, it works.
but I get a new problem, can't search Chinese words. In my fork [repo](https://github.com/taojianjian32/vuepress-plugin-flexsearch/blob/master/example/docs/guide/using-vue.md), I translated `example/docs/guide/using-vue.md`, this page content can't be searched.

**Comment by taojianjian32** [comment]
> Hi, @z3by I checked, It's my mistake, it works.
> but I get a new problem, can't search Chinese words. In my fork [repo](https://github.com/taojianjian32/vuepress-plugin-flexsearch/blob/master/example/docs/guide/using-vue.md), I translated `example/docs/guide/using-vue.md`, this page content can't be searched.

I fixed it by custom flexsearch options.
you can close it, thank you.

**Comment by z3by** [comment]
Awesome!
