### ISSUE TITLE
About support Chinese？

### ISSUE THREAD

**Issue by JohannLai** [z3by/vuepress-plugin-flexsearch#5]
https://github.com/thetre97/gridsome-plugin-flexsearch/issues/23

**Comment by taojunnan** [comment]
you can custom flexsearch default options like
```
      {
        encode: false,
        tokenize: function(str){
            return str.split('');
        }
      }
```

**Comment by JohannLai** [comment]
thank you

**Comment by favoyang** [comment]
@JohannLai @taojunnan @z3by 

Is this still work?

My flexsearch configuration:
```
    [
      "flexsearch",
      {
        searchHotkeys: ["s", "/"],
        search_options: {
          encode: false,
          tokenize: function(str) {
            return str.split("");
          },
          resolution: 9,
          doc: {
            id: "key",
            field: ["title", "content", "headers"]
          }
        }
      }
    ]
```

It seems the tokenize function is not transferred to the client-side after the vuepress build process.

Try to add one a debug log to the setupFlexSearch function:

```
    setupFlexSearch() {
      console.log(SEARCH_OPTIONS.tokenize);
      console.log(SEARCH_OPTIONS);
      this.index = new Flexsearch(SEARCH_OPTIONS);
      const { pages } = this.$site;
      this.index.add(pages);
    },
```

The result is
```
undefined
```
![image](https://user-images.githubusercontent.com/125390/99985253-e4401680-2de8-11eb-943d-5f6dde823754.png)

Env
```
"vuepress-plugin-flexsearch": "^0.1.0",
"vuepress": "^1.5.3",
```

**Comment by favoyang** [comment]
More digging...

SEARCH_OPTIONS is using the `define` parameter of a vuepress plugin.
```
  define: {
    SEARCH_OPTIONS: options.search_options || defaultSearchOptions,
```

According to https://vuepress.vuejs.org/plugin/option-api.html#define

> VuePress opened up a more concise define option, note that the values has been automatically **processed by JSON.stringify.**

That explains why the function has been stripped.

**Comment by favoyang** [comment]
A workaround for search CJK.

```
   [
      "flexsearch",
      {
        search_options: {
          encode: "cjk",
          ...
        }
      }
    ]
```

Using this [patch](https://github.com/openupm/vuepress-plugin-flexsearch/commit/41dcda5f93e080e02ac213c23000027be2df7675) at branch https://github.com/openupm/vuepress-plugin-flexsearch/tree/feat/cjk.

But would be good to have a better way to pass the token function to the client-side.
