### ISSUE TITLE
overlapping search tokens produce broken HTML output

### ISSUE THREAD

**Issue by karottenreibe** [z3by/vuepress-plugin-flexsearch#8]
E.g:

![image](https://user-images.githubusercontent.com/38839/79300381-cb809180-7ee6-11ea-84ce-70b7c1c6a992.png)

The problem is that the search and replace in https://github.com/z3by/vuepress-plugin-flexsearch/blob/b24f602e1b1fcd59b3f78fed0ca1e577830aa90b/SearchBox.vue#L208 does overlapping replacements, i.e. will also replace parts of the inserted html tags.

Code snippet to demonstrate this:

```js
queryWords = ["install", "text"]
querySnippet = "install"
for (const word of queryWords) {
        querySnippet = querySnippet.replace(new RegExp(word, 'gi'), `<strong class="text--primary">${word}</strong>`)
}
```

Running this results in

```js
"<strong class=\"<strong class=\"text--primary\">text</strong>--primary\">install</strong>"
```

(i.e. the "text" of "text--primary" also gets replaced)

**Comment by karottenreibe** [comment]
I took the liberty to create a pull request to fix this :-)

**Comment by z3by** [comment]
Thank you for contributing to this package! @karottenreibe 😄
